# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PHmLfYmkva7UyEYDVakwpciU0IRXNAxF
"""

import socket

target = input("Enter target IP or domain: ")

# Remove protocol if user enters URL
target = target.replace("http://","").replace("https://","")

print("Scanning target:", target)
print("Scanning ports 1 to 1024...\n")

for port in range(1,1025):
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.settimeout(0.5)

    try:
        result = s.connect_ex((target, port))
        if result == 0:
            print("Port", port, "is OPEN")
    except socket.gaierror:
        print("Invalid domain name")
        break

    s.close()